version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "Official Scalingo buildpack - Based on CHH php buildpack, Nginx/PHP-fpm stack"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
